# Practica numpy ndarray
1. Crear ndarrays
2. Operar entre columnas
3. Seleccionar elementos  


# Punto 1

In [14]:
#importar numpy
import numpy as np 

In [8]:
#Crear lista con numeros primos 
numeros_primos =[2,3,5,7,11,13,17,19,23,29]
numeros_primos

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

In [9]:
#Crear arrau a partir de lista 
array_primos=np.array(numeros_primos)
array_primos

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])

In [11]:
#Crear arrays con ceros o como  inicializar un arreglo array
array_zeros=np.zeros(10)
array_zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
#Crear arrays con numeros 
array_numeros = np.arange(10)
array_numeros

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#array con numeros sucesivos (numero inicial, numero final, intervalo)
array_pares = np.arange(0, 20, 2)
array_pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#haciendo un reshape ára dos dimensiones
array_pares.reshape(2,5)


array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

# Punto 2

In [16]:
# Operaciones aritmerticas sobre np array 1-dimension y 2-dimension
array_impares =  array_pares + 1
array_impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [17]:
# multiplicar por 100
array_impares*100

array([ 100,  300,  500,  700,  900, 1100, 1300, 1500, 1700, 1900])

In [18]:
# resta entre arrays
array_impares - array_pares

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#cuidado con la dicision entre 0 
array_impares/array_pares
# cuando se divide entre cero python toma como resultado el inf

C:\Users\USER\AppData\Local\Temp\ipykernel_8548\3745958443.py:2: RuntimeWarning: divide by zero encountered in divide
  array_impares/array_pares


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])

In [20]:
# Metodos asociados a estadistica 
# suma 
array_primos.sum()

np.int64(129)

In [21]:
# promedio 
array_primos.mean()

np.float64(12.9)

In [22]:
# varianza
array_primos.var()

np.float64(73.28999999999999)

In [23]:
# como ordenar un np array  (fibonacci)
array_fibonacci =  np.array([55, 0, 144, 1,21,89,5,8,13,1,34,3,2])
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [24]:
# orden ascendente: de menor a mayor
np.sort(array_fibonacci)

array([  0,   1,   1,   2,   3,   5,   8,  13,  21,  34,  55,  89, 144])

In [25]:
# orden descendente: de mayor a menor
-np.sort(-array_fibonacci)

array([144,  89,  55,  34,  21,  13,   8,   5,   3,   2,   1,   1,   0])

# Punto 3

In [ ]:
# Como seleccionar elements

In [ ]:
#Seleccionar un elemento

In [27]:
A = np.arange(0,20,2).reshape(2,5)
A

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [28]:
# seleccionar el primer elemento 
A[0,0]

np.int64(0)

In [29]:
# seleccionar algún otro elemento 
A[1,3]

np.int64(16)

In [ ]:
# Seleccionar varios elementos
# seleccionar por filas
A[1,:]

array([10, 12, 14, 16, 18])

In [31]:
# seleccionar por columna
A[:,3]

array([ 6, 16])

In [33]:
# Utilizar filter
array_fibonacci

array([ 55,   0, 144,   1,  21,  89,   5,   8,  13,   1,  34,   3,   2])

In [ ]:

# condicion para menores de 20
array_fibonacci < 20

array([False,  True, False,  True, False, False,  True,  True,  True,
        True, False,  True,  True])

In [34]:
# filtar menores de 20
array_fibonacci[array_fibonacci < 20]

array([ 0,  1,  5,  8, 13,  1,  3,  2])